### ISSUE TITLE
Onboarding wizard

### ISSUE THREAD

**Issue by gabrielpoca** [iron-wallet/iron#311]
Whenever anyone opens Iron for the first time, they see something like this:

![Screenshot 2023-07-25 at 13 58 10](https://github.com/iron-wallet/iron/assets/934580/6d64f363-688f-4971-a1e8-18dc804b9617)

It's not a very friendly UI, and there are even some basic things people may need to do before they can use the app. So I propose adding one of those onboarding wizards to ease the process. There is much more that we can do, but this is the first step:

![Onboarding](https://github.com/iron-wallet/iron/assets/934580/c04b52e0-8246-47c3-b10f-3862e5052e47)
![Onboarding-1](https://github.com/iron-wallet/iron/assets/934580/413a7cb9-e90d-4f7c-b63d-fc1a0c674d95)
![Onboarding-2](https://github.com/iron-wallet/iron/assets/934580/51969693-41e9-4701-af01-cc054d50cc50)
![Onboarding-3](https://github.com/iron-wallet/iron/assets/934580/b2570519-fe93-40b4-a811-7ff49596819f)

The idea is to use the components that already exist in MUI library.

Let me know what you think 😁

**Comment by naps62** [comment]
I'll skip comments on copy for now (that's easy to change later, and will likely change alongside the feature anyway)

this is pretty much what I had in mind yes.
I would add one thing though, a new step along the lines of:

- Iron is prepared to connect to anvil nodes, using its default (unsafe) mnemonic. You can opt-out of this behaviour if you don't plan to use it

along with a checkbox where users can opt-out. Keeping it on would mean we add both the "anvil" network and the "test" mnemonic to the settings (right now we add them by default all the time, but that's not very explicit)

**Comment by naps62** [comment]
Is this a good first issue? 🤔 
it involves touching on multiple parts of the code, to grab the different pieces that handle all these various settings. seems a bit heavy-handed for a first issue

**Comment by pferreira101** [comment]
Writing an update on some Onboarding Wizard objectives, as discussed with @naps62 :

Set up the Alchemy key:
- Add a link to Alchemy App's dashboard so that the user can copy the key quicker;
 
Install the browser extension (new step):
- Add a link to a site that points to the browser stores (Chrome and Firefox);
- Detect if the extension is installed;

Check if the user wants to generate a test wallet (new step):
- Add a step asking if the user wishes to use the `test test ... junk` wallet, making it clear it is only for test purposes;

Setting an HD wallet during Onboarding (new step):
- After the test wallet step, show the form for adding an HD wallet (as in Settings/Wallets/Add HD Wallet).

**Comment by naps62** [comment]
I think the current onboarding is already sufficient to consider this issue closed. There are still incremental improvements, and additional steps we can add, but the current approach is miles better already
