### ISSUE TITLE
Refactor the way we handle current wallet address

### ISSUE THREAD

**Issue by DavideSilva** [iron-wallet/iron#426]
Doing a transaction from the Contracts tab, with Fast mode disabled, causes the simulation to break and prevents the transaction to be made. After further exploration and discussion on Slack, we found out the cause of the problem is due to the way we are handling the current wallet address

**Comment by naps62** [comment]
This is a bit off.
The simulation fails because we don't have the `from` address in this case.
it's suposed to be inferred from whatever the address of the connection is. we do have the signer, but never needed the address itself until now.

We also did not have a `wallet.get_address(&path)` function, only a `get_current_path()`, which is not usable here. The fix for the simulation is to add that same `get_address()` and use it when requesting the simulation

The remark about how we handle current address was a sidenote in this context. Since we don't longer have a strong notion of current address for a wallet, I was arguing those methods shouldn't exist on the wallets themselves. Each requester should now either the wallet_path or the address it's trying to use

Anyway, this is now being fixed on #428

**Comment by DavideSilva** [comment]
My point was not only about the simulation but more in general how we are not using the `from` address whenever we make a call from the Contracts tab. Yes, the simulation fails because we don't have a `from` address, but it is also true that any transaction made from the Contracts tab is missing the `from` address, regardless of using the simulation or not
