### ISSUE TITLE
Update CONTRIBUTING.md to include all needed dependencies

### ISSUE THREAD

**Issue by DavideSilva** [iron-wallet/iron#498]
We should explicitly state in CONTRIBUTING that Rust and Foundry are a dependency

**Comment by naps62** [comment]
The CONTRIBUTING file has links that have apparently gone bad (probably because the actual URL is still on the README)

It's supposed to link to tauri's requirements, which includes Rust: https://tauri.app/v1/guides/getting-started/prerequisites/

as for Foundry, can you explain why that is a dependency? I think it's useful to mention it in the guide, but it's not a strict dependency

**Comment by ABZerra** [comment]
Apart from deciding what are the dependencies needed, I don't mind updating this doc if someone is okay with hand-helding me during the "create a PR" process 😂 that way I learn how to do it while still contributing

**Comment by DavideSilva** [comment]
I agree Foundry isn't a strict dependency and I agree we should mention that in the guide
